In [12]:
import pandas as pd
#importing the data using pandas
data=pd.read_csv('D:\\New folder\\stocks.csv',delimiter=',')
#printing the imported data
print(data)
#getting first five records
print(data.head())
#getting last five records
print(data.tail())
#getting information of data
print(data.info())
#getting statistical information of data
descriptive_data = data.describe()
print(descriptive_data)
#removing null values
print(descriptive_data.dropna(axis=0,how='any'))
#removing duplicates
print(descriptive_data.duplicated())
#saving data
descriptive_data.to_csv('stockData.csv',index=False)

    Ticker        Date        Open        High         Low       Close  \
0     AAPL  07-02-2023  150.639999  155.229996  150.639999  154.649994
1     AAPL  08-02-2023  153.880005  154.580002  151.169998  151.919998
2     AAPL  09-02-2023  153.779999  154.330002  150.419998  150.869995
3     AAPL  10-02-2023  149.460007  151.339996  149.220001  151.009995
4     AAPL  13-02-2023  150.949997  154.259995  150.919998  153.850006
..     ...         ...         ...         ...         ...         ...
243   GOOG  01-05-2023  107.720001  108.680000  107.500000  107.709999
244   GOOG  02-05-2023  107.660004  107.730003  104.500000  105.980003
245   GOOG  03-05-2023  106.220001  108.129997  105.620003  106.120003
246   GOOG  04-05-2023  106.160004  106.300003  104.699997  105.209999
247   GOOG  05-05-2023  105.320000  106.440002  104.738998  106.214996

      Adj Close    Volume
0    154.414230  83322600
1    151.688400  64120100
2    150.639999  56007100
3    151.009995  57450700
4    153.850006  62199000
..          ...       ...
243  107.709999  20926300
244  105.980003  20343100
245  106.120003  17116300
246  105.209999  19780600
247  106.214996  20705300

[248 rows x 8 columns]
  Ticker        Date        Open        High         Low       Close  \
0   AAPL  07-02-2023  150.639999  155.229996  150.639999  154.649994
1   AAPL  08-02-2023  153.880005  154.580002  151.169998  151.919998
2   AAPL  09-02-2023  153.779999  154.330002  150.419998  150.869995
3   AAPL  10-02-2023  149.460007  151.339996  149.220001  151.009995
4   AAPL  13-02-2023  150.949997  154.259995  150.919998  153.850006

    Adj Close    Volume
0  154.414230  83322600
1  151.688400  64120100
2  150.639999  56007100
3  151.009995  57450700
4  153.850006  62199000
    Ticker        Date        Open        High         Low       Close  \
243   GOOG  01-05-2023  107.720001  108.680000  107.500000  107.709999
244   GOOG  02-05-2023  107.660004  107.730003  104.500000  105.980003
245   GOOG  03-05-2023  106.220001  108.129997  105.620003  106.120003
246   GOOG  04-05-2023  106.160004  106.300003  104.699997  105.209999
247   GOOG  05-05-2023  105.320000  106.440002  104.738998  106.214996

      Adj Close    Volume
243  107.709999  20926300
244  105.980003  20343100
245  106.120003  17116300
246  105.209999  19780600
247  106.214996  20705300
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Ticker     248 non-null    object
 1   Date       248 non-null    object
 2   Open       248 non-null    float64
 3   High       248 non-null    float64
 4   Low        248 non-null    float64
 5   Close      248 non-null    float64
 6   Adj Close  248 non-null    float64
 7   Volume     248 non-null    int64
dtypes: float64(5), int64(1), object(2)
memory usage: 15.6+ KB
None
             Open        High         Low       Close   Adj Close  \
count  248.000000  248.000000  248.000000  248.000000  248.000000
mean   215.252093  217.919662  212.697452  215.381674  215.362697
std     91.691315   92.863023   90.147881   91.461989   91.454750
min     89.540001   90.129997   88.860001   89.349998   89.349998
25%    135.235004  137.440004  134.822495  136.347498  136.347498
50%    208.764999  212.614998  208.184998  209.920006  209.920006
75%    304.177506  307.565002  295.437500  303.942505  303.942505
max    372.410004  373.829987  361.739990  366.829987  366.829987

             Volume
count  2.480000e+02
mean   3.208210e+07
std    2.233590e+07
min    2.657900e+06
25%    1.714180e+07
50%    2.734000e+07
75%    4.771772e+07
max    1.133164e+08
             Open        High         Low       Close   Adj Close  \
count  248.000000  248.000000  248.000000  248.000000  248.000000
mean   215.252093  217.919662  212.697452  215.381674  215.362697
std     91.691315   92.863023   90.147881   91.461989   91.454750
min     89.540001   90.129997   88.860001   89.349998   89.349998
25%    135.235004  137.440004  134.822495  136.347498  136.347498
50%    208.764999  212.614998  208.184998  209.920006  209.920006
75%    304.177506  307.565002  295.437500  303.942505  303.942505
max    372.410004  373.829987  361.739990  366.829987  366.829987

             Volume
count  2.480000e+02
mean   3.208210e+07
std    2.233590e+07
min    2.657900e+06
25%    1.714180e+07
50%    2.734000e+07
75%    4.771772e+07
max    1.133164e+08
count    False
mean     False
std      False
min      False
25%      False
50%      False
75%      False
max      False
dtype: bool